""" create tanles

Revision ID: 2903eccad21c
Revises: 
Create Date: 2025-08-29 10:17:58.242873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2903eccad21c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('subject_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_index(op.f('ix_subjects_credits'), 'subjects', ['credits'], unique=False)
    op.create_index(op.f('ix_subjects_description'), 'subjects', ['description'], unique=False)
    op.create_index(op.f('ix_subjects_subject_id'), 'subjects', ['subject_id'], unique=False)
    op.create_index(op.f('ix_subjects_subject_name'), 'subjects', ['subject_name'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_role', sa.Enum('HOD', 'STUDENT', 'TEACHER', name='userrole'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=False)
    op.create_index(op.f('ix_users_user_role'), 'users', ['user_role'], unique=False)
    op.create_table('teachers',
    sa.Column('teacher_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('hire_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_index(op.f('ix_teachers_address'), 'teachers', ['address'], unique=False)
    op.create_index(op.f('ix_teachers_first_name'), 'teachers', ['first_name'], unique=False)
    op.create_index(op.f('ix_teachers_hire_date'), 'teachers', ['hire_date'], unique=False)
    op.create_index(op.f('ix_teachers_last_name'), 'teachers', ['last_name'], unique=False)
    op.create_index(op.f('ix_teachers_phone_number'), 'teachers', ['phone_number'], unique=False)
    op.create_index(op.f('ix_teachers_teacher_id'), 'teachers', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_teachers_user_id'), 'teachers', ['user_id'], unique=True)
    op.create_table('departments',
    sa.Column('department_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_name', sa.String(), nullable=False),
    sa.Column('department_code', sa.String(), nullable=False),
    sa.Column('hod_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hod_id'], ['teachers.teacher_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('hod_id')
    )
    op.create_index(op.f('ix_departments_department_code'), 'departments', ['department_code'], unique=True)
    op.create_index(op.f('ix_departments_department_id'), 'departments', ['department_id'], unique=False)
    op.create_index(op.f('ix_departments_department_name'), 'departments', ['department_name'], unique=True)
    op.create_table('teacher_subjects',
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ondelete='CASCADE')
    )
    op.create_table('batches',
    sa.Column('batch_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_name', sa.String(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('seats_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index(op.f('ix_batches_batch_id'), 'batches', ['batch_id'], unique=False)
    op.create_index(op.f('ix_batches_batch_name'), 'batches', ['batch_name'], unique=True)
    op.create_index(op.f('ix_batches_department_id'), 'batches', ['department_id'], unique=False)
    op.create_index(op.f('ix_batches_seats_limit'), 'batches', ['seats_limit'], unique=False)
    op.create_table('department_subjects',
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ondelete='CASCADE')
    )
    op.create_table('department_teachers',
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ondelete='CASCADE')
    )
    op.create_table('batch_subjects',
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ondelete='CASCADE')
    )
    op.create_table('batch_teachers',
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ondelete='CASCADE')
    )
    op.create_table('department_batches',
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ondelete='CASCADE')
    )
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('father_name', sa.String(), nullable=False),
    sa.Column('mother_name', sa.String(), nullable=False),
    sa.Column('roll_number', sa.String(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_index(op.f('ix_students_address'), 'students', ['address'], unique=False)
    op.create_index(op.f('ix_students_batch_id'), 'students', ['batch_id'], unique=False)
    op.create_index(op.f('ix_students_date_of_birth'), 'students', ['date_of_birth'], unique=False)
    op.create_index(op.f('ix_students_department_id'), 'students', ['department_id'], unique=False)
    op.create_index(op.f('ix_students_father_name'), 'students', ['father_name'], unique=False)
    op.create_index(op.f('ix_students_first_name'), 'students', ['first_name'], unique=False)
    op.create_index(op.f('ix_students_last_name'), 'students', ['last_name'], unique=False)
    op.create_index(op.f('ix_students_mother_name'), 'students', ['mother_name'], unique=False)
    op.create_index(op.f('ix_students_phone_number'), 'students', ['phone_number'], unique=False)
    op.create_index(op.f('ix_students_roll_number'), 'students', ['roll_number'], unique=True)
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=False)
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    op.create_table('results',
    sa.Column('result_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.Enum('MIDTERM', 'FINAL', 'QUIZ', 'ASSIGNMENT', name='examtype'), nullable=False),
    sa.Column('marks_obtained', sa.Float(), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('exam_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index(op.f('ix_results_batch_id'), 'results', ['batch_id'], unique=False)
    op.create_index(op.f('ix_results_department_id'), 'results', ['department_id'], unique=False)
    op.create_index(op.f('ix_results_exam_date'), 'results', ['exam_date'], unique=False)
    op.create_index(op.f('ix_results_exam_type'), 'results', ['exam_type'], unique=False)
    op.create_index(op.f('ix_results_grade'), 'results', ['grade'], unique=False)
    op.create_index(op.f('ix_results_result_id'), 'results', ['result_id'], unique=False)
    op.create_index(op.f('ix_results_semester'), 'results', ['semester'], unique=False)
    op.create_index(op.f('ix_results_student_id'), 'results', ['student_id'], unique=False)
    op.create_index(op.f('ix_results_subject_id'), 'results', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_results_subject_id'), table_name='results')
    op.drop_index(op.f('ix_results_student_id'), table_name='results')
    op.drop_index(op.f('ix_results_semester'), table_name='results')
    op.drop_index(op.f('ix_results_result_id'), table_name='results')
    op.drop_index(op.f('ix_results_grade'), table_name='results')
    op.drop_index(op.f('ix_results_exam_type'), table_name='results')
    op.drop_index(op.f('ix_results_exam_date'), table_name='results')
    op.drop_index(op.f('ix_results_department_id'), table_name='results')
    op.drop_index(op.f('ix_results_batch_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_index(op.f('ix_students_roll_number'), table_name='students')
    op.drop_index(op.f('ix_students_phone_number'), table_name='students')
    op.drop_index(op.f('ix_students_mother_name'), table_name='students')
    op.drop_index(op.f('ix_students_last_name'), table_name='students')
    op.drop_index(op.f('ix_students_first_name'), table_name='students')
    op.drop_index(op.f('ix_students_father_name'), table_name='students')
    op.drop_index(op.f('ix_students_department_id'), table_name='students')
    op.drop_index(op.f('ix_students_date_of_birth'), table_name='students')
    op.drop_index(op.f('ix_students_batch_id'), table_name='students')
    op.drop_index(op.f('ix_students_address'), table_name='students')
    op.drop_table('students')
    op.drop_table('department_batches')
    op.drop_table('batch_teachers')
    op.drop_table('batch_subjects')
    op.drop_table('department_teachers')
    op.drop_table('department_subjects')
    op.drop_index(op.f('ix_batches_seats_limit'), table_name='batches')
    op.drop_index(op.f('ix_batches_department_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_batch_name'), table_name='batches')
    op.drop_index(op.f('ix_batches_batch_id'), table_name='batches')
    op.drop_table('batches')
    op.drop_table('teacher_subjects')
    op.drop_index(op.f('ix_departments_department_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_department_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_department_code'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_teachers_user_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_teacher_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_phone_number'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_last_name'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_hire_date'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_first_name'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_address'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_users_user_role'), table_name='users')
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subjects_subject_name'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_subject_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_description'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_credits'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
