""" set exam colm

Revision ID: 2b6dd87071ec
Revises: 6a4095a46a37
Create Date: 2025-09-26 05:38:10.339560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b6dd87071ec'
down_revision: Union[str, Sequence[str], None] = '6a4095a46a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_results_exam_type'), table_name='results')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_results_exam_type'), 'results', ['exam_type'], unique=False)
    # ### end Alembic commands ###
