"""add

Revision ID: 49fd4f998c01
Revises: 276f4e8e99ab
Create Date: 2025-09-25 14:14:27.968191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49fd4f998c01'
down_revision: Union[str, Sequence[str], None] = '276f4e8e99ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batch_teachers')
    op.drop_table('department_subjects')
    op.drop_table('batch_subjects')
    op.drop_table('teacher_subjects')
    op.drop_table('department_teachers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_teachers',
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], name=op.f('department_teachers_department_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], name=op.f('department_teachers_teacher_id_fkey'), ondelete='CASCADE')
    )
    op.create_table('teacher_subjects',
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], name=op.f('teacher_subjects_subject_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], name=op.f('teacher_subjects_teacher_id_fkey'), ondelete='CASCADE')
    )
    op.create_table('batch_subjects',
    sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], name=op.f('batch_subjects_batch_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], name=op.f('batch_subjects_subject_id_fkey'), ondelete='CASCADE')
    )
    op.create_table('department_subjects',
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], name=op.f('department_subjects_department_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], name=op.f('department_subjects_subject_id_fkey'), ondelete='CASCADE')
    )
    op.create_table('batch_teachers',
    sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], name=op.f('batch_teachers_batch_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], name=op.f('batch_teachers_teacher_id_fkey'), ondelete='CASCADE')
    )
    # ### end Alembic commands ###
