""" create tanles

Revision ID: 941fc76f5242
Revises: 2903eccad21c
Create Date: 2025-08-29 11:12:46.509587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '941fc76f5242'
down_revision: Union[str, Sequence[str], None] = '2903eccad21c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department_batches')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_batches',
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], name=op.f('department_batches_batch_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], name=op.f('department_batches_department_id_fkey'), ondelete='CASCADE')
    )
    # ### end Alembic commands ###
