""" change

Revision ID: c3e6da0db5b4
Revises: 949336b6a787
Create Date: 2025-10-10 09:52:08.447360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3e6da0db5b4'
down_revision: Union[str, Sequence[str], None] = '949336b6a787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('departments_hod_id_key'), 'departments', type_='unique')
    op.drop_constraint(op.f('departments_hod_id_fkey'), 'departments', type_='foreignkey')
    op.drop_column('departments', 'hod_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('hod_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('departments_hod_id_fkey'), 'departments', 'teachers', ['hod_id'], ['teacher_id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('departments_hod_id_key'), 'departments', ['hod_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
