""" exam tye

Revision ID: e0c656f39962
Revises: 7d53e8dfcb34
Create Date: 2025-09-28 02:35:12.533735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0c656f39962'
down_revision: Union[str, Sequence[str], None] = '7d53e8dfcb34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('results', 'exam_type',
               existing_type=postgresql.ENUM('MIDTERM', 'FINAL', 'QUIZ', 'ASSIGNMENT', name='examtype'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('results', 'exam_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('MIDTERM', 'FINAL', 'QUIZ', 'ASSIGNMENT', name='examtype'),
               existing_nullable=False)
    # ### end Alembic commands ###
